In [2]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3],  # 2 samples, 3 features
     [11, 12, 13]]
y = [0, 1]  # classes of each sample
clf.fit(X, y)


RandomForestClassifier(random_state=0)

In [15]:
clf.predict(X)

array([0, 1])

In [3]:
from sklearn.datasets import load_diabetes
x, y = load_diabetes(return_X_y=True) # x - данные, y - метки, которые хар-ют запись из набора данных

print('x\n', x[:3])
print('y\n', y[:3])

x
 [[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990749 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632753 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06833155 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567042 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286131 -0.02593034]]
y
 [151.  75. 141.]


In [4]:
from sklearn.model_selection import train_test_split # функция разбивает выборку случ образом на тестовую и обучающую

x_train, x_test, y_train, y_test = train_test_split(x, y) # разбиваются по принципу площадей: (A-b)^2 + b^2 + 2*(A-b)*b, где 1) xtr, 2) ytst, 3) xtst and ytr


In [5]:
from sklearn.preprocessing import StandardScaler # Стандартизация - техника преобразования значений признака (Feature), адаптирующая признаки с разными диапазонами значений. приравнивание среднего значения к нулю или стандартного отклонения к единице (стремление привести данные к нормальному распределению). Стандартизированные данные содержат ту же инфу, но имеют среднее значение 0 и отклонение 1. после масштабирования данных мат. природа алгоритмов позволяет лучше с ними работать (svm k-means)

skaler = StandardScaler().fit(x_train)
stded_X = skaler.transform(x_train)

# print('after:\n', x_train[:3])
print('before:\n', stded_X[:3])


before:
 [[-0.12727     1.05914818  0.57467993  1.09568821  0.80336908  1.16599617
  -0.83507915  1.49382029  0.51257209  0.58777564]
 [-1.6904006  -0.94415495 -0.25855628 -0.15355451 -1.39356952 -1.21662182
  -0.04555845 -0.85375682 -0.86563592 -0.0290161 ]
 [-0.9088353  -0.94415495  1.32020707 -1.32931236 -0.62321443 -0.50774374
  -0.20346259 -0.07123112 -0.03272212  0.41154943]]


Нормализация
В машинном обучениии нормализацией называют метод предобработки числовых признаков в обучающих наборах данных с целью приведения их к некоторой общей шкале без потери информации о различии диапазонов. Нормализация подразумевает изменение диапазонов в данных без изменения формы распределения.
Предположим, у вас есть набор данных с различными единицами: температура в Кельвинах, относительная влажность и день года. Мы можем увидеть следующие диапазоны для каждой функции. Температура



In [6]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer().fit(x_test)
normed_X = scaler.transform(x_test)

# print('after:\n', x_train[:3])
print('before:\n', normed_X[:3])


before:
 [[-0.20427744  0.37908774 -0.05448264 -0.29994037 -0.08378081 -0.10352195
   0.44644443 -0.29541086 -0.61619335 -0.19395917]
 [ 0.17392029  0.54139651  0.02581501 -0.06057497 -0.06085695  0.11642895
  -0.54229388  0.36650854  0.24236458 -0.40974967]
 [-0.35461142 -0.20252502 -0.18462464 -0.36934575 -0.45656089 -0.51171411
   0.10374778 -0.34657776 -0.09205986 -0.23038636]]


In [ ]:
# записываем людях рост, зп и вес

data = [[178, 50000, 58], [130, 20000, 110], [190, 80000, 90]]

scaler = Normalizer().fit(data)
normalized_data = scaler.transform(data)

print('after\n', data[:3])
print('before\n', normalized_data[:3])


Приведение к бинарному виду (Binarization)

Бинаризируйте двнные (установите значения функций равными 0 или 1) в соответствии с пороговым значением.

Например, если мы выберем пороговое значение = 0.5, то значение набора данных выше этого станет 1, а ниже этого станет 0. Поэтому мы можем назвать его бинаризацией данных или пороговым значением данных. Этот метод полезен, когда у нас есть вероятности в нашем наборе данных и мы хотим преобразовать их в чёткие значения.

In [13]:
from sklearn.preprocessing import Binarizer
import numpy as np

X = 10 * np.random.random((5, 5)) - 5

binarizer = Binarizer(threshold=0.0).fit(X) # в данном случае порог 0ю0
binary_X = binarizer.transform(X)

print('after\n', X[:5])
print('before\n', binary_X[:5])

after
 [[-0.80401131 -4.59339794 -4.66954808 -2.06198694  3.6153365 ]
 [ 0.06185149 -1.17780095  1.55733753 -0.63207357  3.45291203]
 [ 2.65268827  1.43531368  0.54893783 -2.88320138 -1.45154197]
 [ 4.23842496 -2.50009701  4.92421932  3.57820278  4.07536693]
 [-2.07038711  1.21315209 -3.11542543 -3.31348183  2.52630498]]
before
 [[0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]]


In [16]:
# Хотим определить прогульщиков (у кого больше N пропусков занятий)

absenteeism_num_student = np.array([[3, 21, 23, 0, 0, 100, 10, 7, 5]]) #  количество прогулов от студентов
binarizer = Binarizer(threshold=7.0).fit(absenteeism_num_student) # порог
binary_absenteeism_num_student = binarizer.transform(absenteeism_num_student)

binary_absenteeism_num_student

array([[0, 1, 1, 0, 0, 1, 1, 0, 0]])

Кодирование категориальных признаков (Encoding categorical features)
Кодируйте целевые метки со значениями от 0 до количество_классов_категорий - 1. Таким образом, мы хотим, например, закодировать строковые значения признака в числовые по категориям

In [22]:
from sklearn.preprocessing import LabelEncoder

y = np.array(['rus', 'usa', 'ua', 'usa', 'rus', 'bel', 'brus', 'en', 'en', 'ru']) # признак - строковые сокращения страны

enc = LabelEncoder()
y = enc.fit_transform(y)

y # теперь для нашей модели все люди из россии в качестве признака Country будет иметь значение 0

array([4, 6, 5, 6, 4, 0, 1, 2, 2, 3])

Загрузка и настройка моделей
Работа с моделями начинается с импорта необходимых нам пакетов, классов, функций

# import
from sklearn.branch import model_name

# create instance
model = model_name()

# fit model
model.fit(X_train, y_train)

Рассмотрим работу моделей для обучения с учителем и без учителя.
При обучении с учителем модель обучается на размеченном наборе данных и предсказывает ответы, которые используются для оценки точности алгоритма на обучающих данных.
При обучении без учителя модель использует неразмеченные данные, из которых алгоритс самостоятельно пытается извлечь признаки и зависимости.

Модели для обучения с учителем
Линейная регрессия (Linear Regression)

Линейная регрессия в машинном обучении - модель зависимости переменной x от одной или нескольких других переменных (факторов, регрессоров, независимых переменных) с линейной функцией зависимости. y = B0 + B1 * x

In [25]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

Метод опорных векторов (SVM, Support Vector Machine)

Работа метода опорных векторов заключается в рисовании линии между разными кластерами точек, которые нужно сгруппировать в классы. С одной стороны линии будут точки, принадлежащие одному классу, с другой стороны - к другому классу

Классификатор будет пытаться учеличить расстояние между рисуемыми линиями и точками на разных сторонах, чтобы увеличить свою уверенность определения класса. Когда все точки построены, сторона, на которую они падают - это класс, которому эти точки принадлежат.

In [ ]:
from sklearn.svm import SVC

svc = SVC(kernel='linear') # указываем тип ядра (linear, poly, rbf, sigmoid, precomputed)


Наивный байесовский классификатор (Naive Bayes)

Классификатор вычисляет вероятность принадлежности объекта к какому-то классу. Эта вероятность вычисляется из шанса, что какое-то событие произойдёт, с опорой на уже произошедшие события

In [26]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

Метод k-ближайших соседей (K Nearest Neighbors)

Этот метод работает с помощью поиска кратчайших дистанций между тестируемым объектом и ближайшими к нему классифицированным объектам из обучающего набора. Классифицируемый объект будет относиться к тому классу, к которому принадлежит ближайший объект набора.


In [ ]:
from sklearn import neighbors

knn = neighbors.KNeighborsClassifier(n_neighbors= 5) # количество соседей

Обучение без учителя (Unsupervised learning)

Метод главных компонент (PCA - principal component analysis)

Метод главных компонент позволяет заменить несколько исходных переменных на меньшее количество новых переменных. Новые искусственные переменные называются главными компонентами.

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)

Метод k-средних (K-Means)

Он разбивает множество элементов векторного пространства на заранее известное число кластеров k. Действие алгоритма таково, что он стремится минимизировать среднеквадратичное отклонение на точках каждого кластера. Основная идея заключается в том, что на каждой итерации перевычисляется центр масс для каждого кластера, полученного на предыдущем шаге, затем векторы разбиваются на кластеры вновь в соответствии с тем, какой из новых центров оказался ближе по выбранной метрике.

In [ ]:
from sklearn.cluster import  KMeans

k_means = KMeans(n_clusters= 3, random_state=0)

Обратим внимание, что у каждой модели есть дополнительные параметры, которые позволяют производить более гибкую настройку модели, что в последствии может повысить её качество


Обучение модели

Обучение модели - это обработка набору данных с использованием некоторого алгоритма, который позволяет анализировать предоставленные данные и запоминать полученные результаты, в некотором смысле делать выводы на основе свойств данных.

В Scilit-learn обучение модели происходит посредством вызова её метода fit, в который в качестве аргумента передаётся набор данных обучающей выборки.

In [37]:
# С учителем
# данные
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]]) # обучающая выборка
y = np.dot(X, np.array([1, 2])) + 3 # тестовая выборка

# создаём объект модели, настраиваем параметры (normalize=true)
lr = LinearRegression()
lr.fit(X, y)
# обучаем модель, передав обучающую выборку X и тестовую выборку y
lr = LinearRegression().fit(X, y)

In [34]:
from sklearn.cluster import  KMeans

# без учителя

X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]]) # обучающая выборка, тестовой нет

kmeans = KMeans(n_clusters=2, random_state=0) # создаём объект модели, настраиваем параметры
kmeans = kmeans.fit(X) # обучаем модель

/home/divan/.local/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Предскажем будущее?
После обучения модель способна спрогнозировать результат для новых данных с помощью методов модели predict, predict_proba

In [42]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]]) # данные для обучения

kmeans = KMeans(n_clusters=2, random_state=0)
kmeans = kmeans.fit(X)

# тестовые или новые данные для которых мы хотим получить предсказание
test = np.array([[5, 1], [10, 3], [2, 1], [11, 1], [9, 3], [9, 1]])

y = kmeans.predict(test) # предсказываем)

print('predict: ', y)

/home/divan/.local/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


predict:  [1 0 1 0 0 0]


In [45]:
from sklearn import neighbors

X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]]) # данные для обучения

Y = np.array([1, 1, 1, 0, 0, 0]) # тестовые

knn = neighbors.KNeighborsClassifier()
knn = knn.fit(X, Y)

# тестовые или новые данные для которых мы хотим получить предсказание
test = np.array([[5, 1], [10, 3], [2, 1], [11, 1], [9, 3], [9, 1]])

y = knn.predict_proba(test) # предсказываем)

print('predict: ', y) # оцениваем вероятность появления метки

predict:  [[0.4 0.6]
 [0.6 0.4]
 [0.4 0.6]
 [0.6 0.4]
 [0.6 0.4]
 [0.6 0.4]]


Оценка качества модели

Оценка качества модели выполняется с использованием тестировых выборки. Проверяется насколько точно модели предсказывает результат на тестовых данных, для которых известны правильные метки. Как правило, используется модуль metrics или встроенные методы модели.

# import
from sklearn.metrics import metric_name

# create instance
metric_name(y_test, model.predict(X_test)) # где y_test - real target, predict - predicted target



metrics scikit learn:

        1) classification:

                a) accuracy_score
                b) balanced_accuracy_score
                c) average_precision_score
                d) brier_score_loss
                e) f1_score
                f) log_loss
                g) precision_score
                h) recall_score
                i) jaccard_score
                j) roc_auc_score

        2) regression:

                a) explained_variance_score
                b) max_error
                c) mean_absolute_error
                d) mean_squared_error
                e) mean_squared_log_error
                f) median_absolute_error
                g) r2_score
                h) mean_poisson_deviance
                i) mean_gamma_deviance

In [70]:
# accuracy_score
from sklearn.metrics import accuracy_score
print('liked function accuracy_score')

y_pred = [1, 0, 0, 1]
y_true = [0, 0, 1, 1]

accuracy_score(y_true, y_pred)

liked function accuracy_score


0.5